CREATE TABLE Test(ID int(5), Kythuatxetnghiem NVARCHAR(255),Thoigianxetnghiem VARCHAR(10),Thoigiantraketqua VARCHAR(10));
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (1,'Định lượng Glucose máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (2,'Định lượng Ure máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (3,'Định lượng Creatinin máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (4,'Định lượng Albumin máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (5,'Định lượng Protein máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (6,'Định lượng Acid Uric máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (7,'Định lượng Cholesterol máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (8,'Định lượng HDL_C máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (9,'Định lượng Triglycerid máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (10,'Đo hoạt độ LDH máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (11,'Đo hoạt độ  ALP máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (12,'Đo hoạt độ Amylase máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (13,'Đo hoạt độ GGT máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (14,'Đo hoạt độ GOT','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (15,'Đo hoạt độ GPT','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (16,'Điện giải đồ( Na+ K+ Cl-)','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (17,'Định lượng Fe huyết thanh','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (18,'Định lượng CRP máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (19,'Định lượng NH3 máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (20,'Định lượng Ethanol máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (21,'Định lượng Lipid máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (22,'Định lượng Beta 2 Microglobulin máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (23,'Định lượng Calci máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (24,'Đo hoạt độ CK máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (25,'Định lượng CK-MB máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (26,'Định lượng IgA máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (27,'Định lượng IgG máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (28,'Định lượng  IgE máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (29,'Định lượng IgM máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (30,'Định lượng   Kappa máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (31,'Định lượng Lamda  máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (32,'Định lượng IgM máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (33,'Định lượng Bilirubin trực tiếp máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (34,'Định lượng Bilirubin toàn phần máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (35,'Định lượng ASLO máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (36,'Định lượng RF máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (37,'Định lượng AFP máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (38,'Định lượng Anti-HBs máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (39,'Định lượng Anti-Tg máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (40,'Định lượng Anti-TPO máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (41,'Định lượng Beta HCG máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (42,'Định lượng CA125 máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (43,'Định lượng CA15-3 máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (44,'Định lượng CA19-9 máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (45,'Định lượng CEA máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (46,'Định lượng Cortisol máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (47,'Định lượng Cyfra 21-1 máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (48,'Định lượng Ferritin máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (49,'Định lượng Free- PSA máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (50,'Định lượng  Total PSA máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (51,'Định lượng Free T4 máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (52,'Định lượng Total T3 máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (53,'Định lượng TSH máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (54,'Định lượng HBeAg máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (55,'HbsAg miễn dịch tự động','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (56,'Anti-HCV miễn dịch tự động','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (57,'Anti-HIV miễn dịch tự động','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (58,'Định lượng Syphilis máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (59,'Định lượng Pepsinogen  máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (60,'Định lượng PTH máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (61,'Định lượng SCC máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (62,'Định lượng Hs Troponin I máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (63,'Định lượng Pro GRP máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (64,'Định lượng HbA1c máu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (65,'Tổng phân tích nước tiểu','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (66,'Phản ứng Rivalta','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (67,'Thời gian thromboplastin hoạt hoá từng phần (APTT)','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (68,'Thời gian prothrombin (PT: Prothrombin Time), (Các tên khác: TQ; Tỷ lệ Prothrombin) bằng máy tự động','5p','sau 1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (69,'Nhuộm hồng cầu lưới trên máy tự động','5p','1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (70,'Tổng phân tích tế bào máu ngoại vi bằng máy đếm laser','5p','1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (71,'Xét nghiệm số lượng và độ tập trung tiểu cầu (bằng máy đếm laser)','5p','1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (72,'Tìm ký sinh trùng sốt rét trong máu (bằng phương pháp thủ công)','5p','1h30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (73,'Nội soi tai mũi họng','15p','10p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (74,'Nội soi can thiệp - làm Clo test chẩn đoán nhiễm H.Pylori','30p','10p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (75,'Nội soi đại trực tràng toàn bộ ống mềm có dùng thuốc gây mê','1h','10p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (76,'Điện tim thường','10p','10p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (77,'Đo Chức năng hô hấp','30p','10p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (78,'Siêu âm','30p','30p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (79,'Chụp cắt lớp vi tính','1h30','10p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (80,'Chụp Xquang','45p','10p');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (81,'Chọc hút tế bào tuyến giáp dưới hướng dẫn siêu âm','15p','3h');
INSERT INTO Test (ID,Kythuatxetnghiem,Thoigianxetnghiem,Thoigiantraketqua) VALUES (82,'Sinh thiết hạch (hoặc u) duới hướng dẫn siêu âm','45p','7-10 ngày');