<fscreen>

	canvas.before:
		Color:
			rgba: 1, 1, 1, 1

		Rectangle:
			size: root.width, root.height
			pos: 0, 0



	ScrollView:
		size: root.width*0.4, root.height*0.4
		pos: root.height*0.3, root.height*0.3
        Label:
            text:"Điền thông tin cá nhân"
            # text_size: root.width, None
            font_size:"30sp"
            color: (228/255, 95/255, 43/255, 1)
            halign:'center'
            # valign: 'top'
            # padding: dp(25)
            bold: True

        ScrollView:

            MDTextField:
                mode: "fill"
                hint_text: "Họ và tên:"
                helper_text:"Nhập đầy đủ họ và tên"
                helper_text_mode: "on_focus"
                # required: True


            MDGridLayout:
                rows:2
                size_hint_y:.10
                col_default_width: self.width/3
                adaptive_height: True

                MDLabel:
                    text:"Giới tính:"   
                    

                MDGridLayout:
                    # size_hint_y:.001
                    cols:3
                    col_default_width: self.width/3
                    adaptive_height: True
                    # md_bg_color: app.theme_cls.primary_color
                    padding:[dp(15),dp(15),dp(15),dp(5)]

                    MDGridLayout:
                    # size_hint_y:.001
                        cols:2
                        # col_default_width: self.width/3
                        adaptive_height: True

                        MDCheckbox:
                            size_hint: None, None
                            size: "48dp", "48dp"
                            pos_hint: {'center_x': .5, 'center_y': .5}  
                            group: 'sex'
                            color: [228/255, 95/255, 43/255, 1]

                        MDLabel:
                            text:"Nam"

                        





	# TextInput:
	# 	id: input
	# 	size: root.width*0.6, root.height*0.05
	# 	pos: root.width*0.2, root.height*0.2
	# 	hint_text: 'Push me To scroll'


	# Button:
	# 	text: ' push me'
	# 	size: root.width*0.4, root.height*0.05
	# 	pos: root.width*0.3, root.height*0.1
	# 	on_press: root.push_me()